language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

python:
  - 3.6
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no --set quiet true
  - conda config --add channels conda-forge
  - conda update conda --yes


install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda install --file requirements.txt
  - conda install --file test_requirements.txt

script:
  - set -e
  - ff_ci_pr_build --help
  - upload_or_check_non_existence --help
  - setup_conda_rc --help
  - upload_package --help
  - make_build_number --help
